# Generated by Django 4.2.5 on 2023-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
